# Generated by Django 5.2.12 on 2026-04-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(default='Steam', max_length=50),
        ),
    ]
