# Generated by Django 5.2.12 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
